config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create, :landing, :destroy]

  get '/students/troubled' => 'students#troubled'
  get '/students/:id/history' => 'students#history', as: 'student_history'
  get 'students/:id/contact' => 'students#contact', as: 'student_contact'

  resources :cohorts, only: [:index] do
    resources :students, only: [:index, :show]
    resources :attendances, only: [:show, :index, :edit, :update]
  end
  post '/email/:producer_id' => 'email#create'

  get '/email' => 'notification#new'

  # post 'twilio/voice' => 'twilio#voice'
  get '/notifications/receive' => 'notifications#receive'

  resources :users, only: [:index, :get, :edit, :update, :show]
  get '/users/:id/edit_pass' => 'users#edit_pass', as: 'user_edit_pass'
  patch '/users/:id/update_pass' => 'users#update_pass', as: 'user_update_pass'
  # post '/users/:id/edit', :to => 'users#edit'

  root 'sessions#landing'

  get    '/login' => 'sessions#new'
  post   '/login' => 'sessions#create'
  delete '/login' => 'sessions#destroy'
 
end
 

app/views/buttons/_all_cohorts.html.erb
<%= form_tag('/cohorts', method: 'get') do %>
  <button type="submit" class="all-cohorts">My Cohorts</button>
<% end %>

app/views/buttons/_cohort_view.html.erb
<%= form_tag(cohort_students_path(@current_user.cohort_id), method: 'get') do %>
  <button type="submit" class="cohort-view">My Cohort</button>

<% end %>

app/views/buttons/_contact_producer.html.erb
            
<%= form_tag(student_contact_path(@current_user), method: 'get') do %>
  <button type="submit" class="contact-producer">Contact Producer</button>
<% end %>

app/views/buttons/_date_picker.html.erb
<div class="date-picker">
	<form action="/cohorts/<%= params[:cohort_id] || @current_user.cohort_id %>/attendances/" method ="GET"class="search-date">
	  <button type="submit" id="go-to">Go to Date</button>
	  <input type="text" name="date" placeholder="enter date" id="date-picker">
	</form>
</div>

<script>
	var dateHighlight = function() {
		$('#date-picker').addClass('date-highlight');
	}
	var dateUnhighlight = function() {
		$('#date-picker').removeClass('date-highlight');
	}

	$('#go-to').hover(dateHighlight, dateUnhighlight);

	var validateDate = function(e) {
		if ($('#date-picker').val() === '') {
			e.preventDefault();
		}
	}

	$('#go-to').click(validateDate)
</script>

app/views/buttons/_edit_profile.html.erb
<%= form_tag(user_path(@current_user), method: 'get') do %>
  <button type="submit" class="my-profile">My Profile</button>
<% end %>

app/views/buttons/_logout.html.erb
<%= form_tag('/login', method: 'delete') do %>
  <button type="submit" class="logout">Log Out</button>
<% end %>

app/views/buttons/_student_history.html.erb
            
<%= form_tag(cohort_student_path(@current_user.cohort_id, @current_user.id), method: 'get') do %>
  <button type="submit" class="student-history">Student History</button>
<% end %>

app/views/buttons/_today.html.erb
<%= form_tag(edit_cohort_attendance_path(@current_user.cohort_id, Date.today), method: 'get') do %>
	<button type="submit" class="today">Today's Attendance</button>
<% end %>

app/views/buttons/_troubled_students.html.erb
<%= form_tag(students_troubled_path, method: 'get') do %>
  <button type="submit" class="flagged-students">Flagged Students</button>
<% end %>