config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create, :landing, :destroy]

  get '/students/troubled' => 'students#troubled'
  get '/students/:id/history' => 'students#history', as: 'student_history'
  get 'students/:id/contact' => 'students#contact', as: 'student_contact'

  resources :cohorts, only: [:index] do
    resources :students, only: [:index, :show]
    resources :attendances, only: [:show, :index, :edit, :update]
  end
  post '/email/:producer_id' => 'email#create'

  get '/email' => 'notification#new'

  # post 'twilio/voice' => 'twilio#voice'
  get '/notifications/receive' => 'notifications#receive'

  resources :users, only: [:index, :get, :edit, :update, :show]
  get '/users/:id/edit_pass' => 'users#edit_pass', as: 'user_edit_pass'
  patch '/users/:id/update_pass' => 'users#update_pass', as: 'user_update_pass'
  # post '/users/:id/edit', :to => 'users#edit'

  root 'sessions#landing'

  get    '/login' => 'sessions#new'
  post   '/login' => 'sessions#create'
  delete '/login' => 'sessions#destroy'
 
end
 

app/models/user.rb
class User < ActiveRecord::Base
	validates :email, uniqueness: true
	has_secure_password

	def student?
		self.type == 'Student'
	end

	def instructor?
		self.type == 'Instructor'
	end

	def producer?
		self.type == 'Producer'
	end

end#U

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authorize

	def index
		@users = User.all
	end

	def get
	end

	def show
		current_user
		@user = User.find(params[:id])
	end

	def edit
		current_user
		@user = User.find(params[:id])
		if current_user.id == @user.id
			render :edit
		else
			render :show
		end
	end

	def update
		current_user
		@user = User.find(params[:id])
		if @user.instructor?
			info = params['instructor']
		elsif @user.student?
			info = params['student']
		elsif @user.producer?
			info = params['producer']
		end
    if @user.update(info.permit(:name, :email, :phone_num))
      redirect_to "/users/#{@user.id}"
    else
      render :edit
    end
	end

	def edit_pass
		@user = User.find(params[:id])
		if current_user.id == @user.id
			render :edit_pass
		else
			render :show
		end
	end

	def update_pass
		current_user
		if current_user.instructor?
			info = params['instructor']
		elsif current_user.student?
			info = params['student']
		elsif current_user.producer?
			info = params['producer']
		end
		user = User.find(current_user.id)
  	if user.update(info.permit(:password, :password_confirmation))
  		redirect_to "/users/#{user.id}"
  	else
  		render :edit_pass
  	end
	end

	private

end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_url(email, size)
	  gravatar_id = Digest::MD5::hexdigest(email).downcase
	  default_url = "http://i.dailymail.co.uk/i/pix/2011/06/10/article-2001697-0C816FEB00000578-38_306x423.jpg"
	  url = "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}&d=#{CGI::escape(default_url)}"
	end
end

app/views/users/_formPassword.html.erb
<div class="edit">
	<%= form_for @current_user, url: user_update_pass_path(@current_user) do |form| %>
		<%= form.label :new_password, "new password" %><br>
		<%= form.password_field :password %><br>
		<%= form.label :password_confirmation, "password confirmation" %><br>
		<%= form.password_field :password_confirmation %><br>
		<%= form.submit 'Update Password' %>
<% end %>
</div>

app/views/users/_formProfile.html.erb
<div class="edit">
<%= form_for @user, url: user_path(@user) do |form| %>
	<div>
		<%= form.label :name %><br />
		<%= form.text_field :name %>
	</div>

	<div>
		<%= form.label :email %><br />
		<%= form.text_field :email %>
	</div>

	<div>
		<%= form.label :phone_number %><br />
		<%= form.text_field :phone_num %>
	</div>

	<div class="action">
	 		<%= form.submit 'Save Profile' %>
	</div>
<% end %>
</div>
<!-- this needs to get worked on after lunch. -->

app/views/users/_gravatar.html.erb
<div class="pro-pic">
	<%= image_tag gravatar_url(@user.email, '150x150'), id: 'gravatar' %>
</div>

app/views/users/edit.html.erb
<div class="tr heading">
	Edit Profile
</div>
<%= render 'formProfile' %>

app/views/users/edit_pass.html.erb
<div class="tr heading">
  Edit Password
</div>
<%= render 'formPassword' %>

app/views/users/index.html.erb
<div class="tr heading">
	All Users
</div>
<div class="table">
<% @users.each do |user| %>
	<div class="cohort">
		<%= link_to "#{user.name} | #{user.type}", user_path(user) %>
	</div>
<% end %>
</div>

app/views/users/show.html.erb
<div class="tr heading">
	Profile: <%= @user.name %>
</div>

<div class="profile">
	<%= render 'gravatar' %>	

	<div class="pro-text"> 
	<p><span>&nbsp;Name&nbsp;</span>&nbsp;<%= @user.name %></p>
	<p><span>&nbsp;User&nbsp;</span>&nbsp;<%= @user.type %></p> 
	<p><span>&nbsp;Email&nbsp;</span>&nbsp;<%= @user.email %></p>
	<p><span>&nbsp;Phone#&nbsp;</span>&nbsp;<%= @user.phone_num %></p>
	<% if @current_user.id == params[:id].to_i %>
		<div class="profile-footer">
			<%= link_to "edit profile", edit_user_path(current_user), :class => "button"  %>
			<%= link_to "change password", user_edit_pass_path(current_user), :class => "button" %>
		</div>
	<% end %>
	</div>

	
</div>

<script type="text/javascript">
    $(".my-profile").addClass('ghosted');
</script>