config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create, :landing, :destroy]

  get '/students/troubled' => 'students#troubled'
  get '/students/:id/history' => 'students#history', as: 'student_history'
  get 'students/:id/contact' => 'students#contact', as: 'student_contact'

  resources :cohorts, only: [:index] do
    resources :students, only: [:index, :show]
    resources :attendances, only: [:show, :index, :edit, :update]
  end
  post '/email/:producer_id' => 'email#create'

  get '/email' => 'notification#new'

  # post 'twilio/voice' => 'twilio#voice'
  get '/notifications/receive' => 'notifications#receive'

  resources :users, only: [:index, :get, :edit, :update, :show]
  get '/users/:id/edit_pass' => 'users#edit_pass', as: 'user_edit_pass'
  patch '/users/:id/update_pass' => 'users#update_pass', as: 'user_update_pass'
  # post '/users/:id/edit', :to => 'users#edit'

  root 'sessions#landing'

  get    '/login' => 'sessions#new'
  post   '/login' => 'sessions#create'
  delete '/login' => 'sessions#destroy'
 
end
 

app/models/producer.rb
class Producer < User
	has_many :cohorts
end

app/controllers/producers_controller.rb
class ProducersController < ApplicationController

	def new
	end

	def show
		@producer = Producer.find(params['id'])
	end

	def edit
	end

end

app/views/producers/show.html.erb
<h1>Welcome back <%= @producer.name %> !!!</h1>
<%= link_to 'See the cohorts', cohorts_path %>

<form action="MAILTO:bensayeg@gmail.com" method="post" enctype="text/plain">
Name:<br>
<input type="text" name="name" value="your name"><br>
E-mail:<br>
<input type="text" name="mail" value="your email"><br>
Comment:<br>
<input type="text" name="comment" value="your comment" size="50"><br><br>
<input type="submit" value="Send">
<input type="reset" value="Reset">
</form>