config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create, :landing, :destroy]

  get '/students/troubled' => 'students#troubled'
  get '/students/:id/history' => 'students#history', as: 'student_history'
  get 'students/:id/contact' => 'students#contact', as: 'student_contact'

  resources :cohorts, only: [:index] do
    resources :students, only: [:index, :show]
    resources :attendances, only: [:show, :index, :edit, :update]
  end
  post '/email/:producer_id' => 'email#create'

  get '/email' => 'notification#new'

  # post 'twilio/voice' => 'twilio#voice'
  get '/notifications/receive' => 'notifications#receive'

  resources :users, only: [:index, :get, :edit, :update, :show]
  get '/users/:id/edit_pass' => 'users#edit_pass', as: 'user_edit_pass'
  patch '/users/:id/update_pass' => 'users#update_pass', as: 'user_update_pass'
  # post '/users/:id/edit', :to => 'users#edit'

  root 'sessions#landing'

  get    '/login' => 'sessions#new'
  post   '/login' => 'sessions#create'
  delete '/login' => 'sessions#destroy'
 
end
 

app/models/attendance.rb
class Attendance < ActiveRecord::Base
	belongs_to :student

end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
	before_action :authorize

	def index
		date = params[:date]
		# date_to_use = params[:date].to_s
		# datetime = DateTime.strptime(date_to_use, "%m/%d/%Y")
		# date = datetime.strftime("%Y-%m-%d") # reformat datetime and assign it to date
			# date = Date.parse(params[:date]).strftime("%d-%m-%Y")

		if current_user.instructor? 
  		redirect_to "/cohorts/#{@current_user.cohort_id}/attendances/#{date}/edit"
		elsif current_user.producer?
  		redirect_to "/cohorts/#{params[:cohort_id]}/attendances/#{date}" 
		end

	end
=begin
	clicking on go to date with no dates specified throws an error.
	invalid date has returned, needs rebase.
# wip
		# begin
  # 		specify the var and run the code that might throw an error
		#rescue ArgumentError #=> e
  		#flash[:error] = e.message # didn't add a message, KISS.
  		redirect_to "/cohorts/" + params[:cohort_id] + "/students"
=end
	def show
		current_user
		@cohort = Cohort.find(params[:cohort_id])
		@attendance = Attendance.joins(:student).includes(:student).where(:date => params[:id], :users => {:cohort_id => params[:cohort_id]})
		@today = Date.today
		if @current_user.producer?  
			@cohort = Cohort.find(params[:cohort_id])
			@students = @cohort.students
		elsif @current_user.instructor?
			@cohort = Cohort.find(@current_user.cohort_id)
			@students = @cohort.students
		
		elsif @current_user.student?
			redirect_to cohort_stusdent_path(user.cohort_id, user.id)
		else
			redirect_to 'cohort'
		end
	end

	def edit
		# @today = Date.today
		@cohort = Cohort.find(params[:cohort_id])
		@attendances = Attendance.joins(:student).includes(:student).where(:date => params[:id], :users => {:cohort_id => params[:cohort_id]})
	end

	def update
		students = params[:students]

		students.each do |s|

			student = Student.find(s[0])
			

			attendance = Attendance.where({student_id: s[0], date: params[:id]}).first
			attendance.present = (s[1][:presence] == 'present' ? true : false)
			attendance.late = (s[1][:presence] == 'late' ? true : false)
			attendance.absent = (s[1][:presence] == 'absent' ? true : false)
			attendance.excused = (s[1][:excused].nil? ? false : true)		

			attendance.save
			if student.flagged? && !student.was_flagged?
				NotificationMailer.alert_troubled_student(student).deliver_now
			end

		end
		redirect_to "/cohorts/#{params[:cohort_id]}/attendances/#{params[:id]}/edit"
	end

# 	private

# 	def set_cohort
# 		@cohort = Cohort.find(params[:cohort_id])
# 	end
# end

end

app/views/attendances/_attendance.html.erb
<div class="attendance">
		<%= attendance.student.name %>
		<%= attendance.date %>
		<%= attendance.absent %>
</div>
 <!-- This is the template for the attendance, which will be served to the rest of the views as partials via render. -->

 <!-- Not using @ because its similar to global var and is considered bad practice, someone who knows this better can change the code above. -->

app/views/attendances/edit.html.erb
<!-- NAVIGATION -->

<!-- MAIN CONTENT -->
<div class="tr heading">
	Cohort: <%= @cohort.name %> | 
		<% if @attendances.first.nil? %> 
			Date: N/A
		<% else %>
			Date: <%= @attendances.first.date %>
		<% end %>
</div>
<div class="table-head">
	<div class="tr">
		<div class="td name">Student</div>
		<div class="td check">Present</div>
		<div class="td check">Late</div>
		<div class="td check">Absent</div>
		<div class="td check">Excused</div>
	</div>
</div>
<div class="table">
	<%= form_tag cohort_attendance_path(@cohort, params[:id]), method: "patch" do %>
		<% @attendances.each_with_index do |attendance, i| %>
			<% even_odd = ((i % 2 == 0) ? 'even' : 'odd')%>
			<div class="tr <%= even_odd %>">
				<div class="td name">
					<p><%= attendance.student.name %></p>
				</div>
				<!-- each row needs to be in its own for it to have one selection only -->
				<div class="td check">
					<input type="radio" name="students[<%= attendance.student_id %>][presence]" value="present" <%= attendance.present == true ? "checked='checked'" : nil %> >
					<label for="present">present</label>
				</div>
				<div class="td check">
					<input type="radio" name="students[<%= attendance.student_id %>][presence]" value="late" <%= attendance.late == true ? "checked='checked'" : nil %> >
					<label for="late">late</label>
				</div>
				<div class="td check">
					<input type="radio" name="students[<%= attendance.student_id %>][presence]" value="absent" <%= attendance.absent == true ? "checked='checked'" : nil %> >
					<label for="absent">absent</label>
				</div>
				<div class="td check">
					<input type="radio" name="students[<%= attendance.student_id %>][presence]" value="excused" <%= attendance.excused == true ? "checked='checked'" : nil %> >
					<label for="excused">excused</label>
				</div>
				<!-- placement marker ==================== -->
			</div>
		<% end %>
		<div class="tr">
			<div class="flex-horizontal"></div>
			<button type="submit" id="saved" class="submit">SAVE</button>
		</div>
	<% end %>
</div>
<% if @attendances.first.nil? %>
	<div class="student-message"><p>No scheduled classes for this date</p></div>
	<script>$('.submit').hide()</script>
<% end %>

<% if Date.today.to_s == params[:id] %>
  <script type="text/javascript">
      $(".today").addClass('ghosted');
  </script>
<% end %>

app/views/attendances/show.html.erb
<div class="tr heading">
	Cohort: <%= @cohort.name %> | Date: <%= @attendances.first.date %>	<!-- params[:date]  -->
</div>

<div class="table-head">
	<div class="td name">
		Student
	</div>
<!-- 	<div class="td date">
		Date
	</div> -->
	<div class="td check">
		Present
	</div>
	<div class="td check">
		Late
	</div>
	<div class="td check">
		Absent
	</div>
	<div class="td check">
		Excused
	</div>
</div>
<div class="table">
	<% @attendances.each_with_index do |attendance, i| %>
		<% even_odd = ((i % 2 == 0) ? 'even' : 'odd')%>
		<div class="tr <%= even_odd %>">
			<div class="td name">
				<%= attendance.student.name %>
			</div>
			<!-- <div class="td date">
				<%= attendance.date %>
			</div> -->
			<div class="td check">
				<%= attendance.present %>
			</div>
			<div class="td check">
				<%= attendance.late %>
			</div>
			<div class="td check">
				<%= attendance.absent %>
			</div>
			<div class="td check">
				<%= attendance.excused %>
			</div>
		</div>
	<% end %>
</div>
<!-- attendance list -->

<% if Date.today.to_s == params[:id] %>
  <script type="text/javascript">
      $(".today").addClass('ghosted');
  </script>
<% end %>